# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handover.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from qtpy.QtCore import Qt
from PyQt5.QtCore import QFileInfo
from PyQt5.QtWidgets import (QApplication, QWidget, QTableWidget, QMainWindow,
                             QTableWidgetItem, QAbstractItemView, QFileDialog)
import pandas as pd


class Ui_HandOver(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1082, 513)
        self.Form = Form
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(450, 10, 311, 21))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 130, 1041, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(20, 190, 1041, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 50, 751, 82))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ReceDeptName = QtWidgets.QComboBox(self.widget)
        self.ReceDeptName.setEnabled(False)
        self.ReceDeptName.setObjectName("ReceDeptName")
        self.gridLayout.addWidget(self.ReceDeptName, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.RecePerson_A = QtWidgets.QLineEdit(self.widget)
        self.RecePerson_A.setEnabled(False)
        self.RecePerson_A.setObjectName("RecePerson_A")
        self.gridLayout.addWidget(self.RecePerson_A, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.SuperPerson = QtWidgets.QLineEdit(self.widget)
        self.SuperPerson.setEnabled(False)
        self.SuperPerson.setObjectName("SuperPerson")
        self.gridLayout.addWidget(self.SuperPerson, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 6, 1, 1)
        self.MoveDate = QtWidgets.QDateEdit(self.widget)
        self.MoveDate.setEnabled(False)
        self.MoveDate.setObjectName("MoveDate")
        self.gridLayout.addWidget(self.MoveDate, 0, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.MoveDeptName = QtWidgets.QComboBox(self.widget)
        self.MoveDeptName.setEnabled(False)
        self.MoveDeptName.setObjectName("MoveDeptName")
        self.gridLayout.addWidget(self.MoveDeptName, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.MovePerson_A = QtWidgets.QLineEdit(self.widget)
        self.MovePerson_A.setEnabled(False)
        self.MovePerson_A.setObjectName("MovePerson_A")
        self.gridLayout.addWidget(self.MovePerson_A, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.MoveSeal = QtWidgets.QComboBox(self.widget)
        self.MoveSeal.setEnabled(False)
        self.MoveSeal.setObjectName("MoveSeal")
        self.gridLayout.addWidget(self.MoveSeal, 1, 5, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.reason = QtWidgets.QComboBox(self.widget)
        self.reason.setEnabled(False)
        self.reason.setObjectName("reason")
        self.gridLayout.addWidget(self.reason, 2, 1, 1, 3)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(810, 40, 195, 91))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pt_new = QtWidgets.QPushButton(self.widget1)
        self.pt_new.setObjectName("pt_new")
        self.gridLayout_2.addWidget(self.pt_new, 0, 0, 1, 1)
        self.pt_add = QtWidgets.QPushButton(self.widget1)
        self.pt_add.setEnabled(False)
        self.pt_add.setObjectName("pt_add")
        self.gridLayout_2.addWidget(self.pt_add, 0, 1, 1, 1)
        self.pt_change = QtWidgets.QPushButton(self.widget1)
        self.pt_change.setEnabled(False)
        self.pt_change.setObjectName("pt_change")
        self.gridLayout_2.addWidget(self.pt_change, 1, 0, 1, 1)
        self.pt_del = QtWidgets.QPushButton(self.widget1)
        self.pt_del.setEnabled(False)
        self.pt_del.setObjectName("pt_del")
        self.gridLayout_2.addWidget(self.pt_del, 1, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(20, 150, 844, 26))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.widget2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.DocuDate_s = QtWidgets.QDateEdit(self.widget2)
        self.DocuDate_s.setObjectName("DocuDate_s")
        self.horizontalLayout.addWidget(self.DocuDate_s)
        self.label_11 = QtWidgets.QLabel(self.widget2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.DocuDate_e = QtWidgets.QDateEdit(self.widget2)
        self.DocuDate_e.setObjectName("DocuDate_e")
        self.horizontalLayout.addWidget(self.DocuDate_e)
        self.label_12 = QtWidgets.QLabel(self.widget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.RecePerson_B = QtWidgets.QLineEdit(self.widget2)
        self.RecePerson_B.setObjectName("RecePerson_B")
        self.horizontalLayout.addWidget(self.RecePerson_B)
        self.label_13 = QtWidgets.QLabel(self.widget2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.MovePerson_B = QtWidgets.QLineEdit(self.widget2)
        self.MovePerson_B.setObjectName("MovePerson_B")
        self.horizontalLayout.addWidget(self.MovePerson_B)
        self.label_14 = QtWidgets.QLabel(self.widget2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.SealName_B = QtWidgets.QComboBox(self.widget2)
        self.SealName_B.setObjectName("self.SealName_B")
        self.horizontalLayout.addWidget(self.SealName_B)
        self.widget3 = QtWidgets.QWidget(Form)
        self.widget3.setGeometry(QtCore.QRect(870, 150, 195, 30))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pt_query = QtWidgets.QPushButton(self.widget3)
        self.pt_query.setObjectName("pt_query")
        self.horizontalLayout_2.addWidget(self.pt_query)
        self.pt_print = QtWidgets.QPushButton(self.widget3)
        self.pt_print.setObjectName("pt_print")
        self.horizontalLayout_2.addWidget(self.pt_print)
        self.DocuDate_e.setDisplayFormat('yyyy/MM/dd')
        self.DocuDate_s.setDisplayFormat('yyyy/MM/dd')
        self.area_A = [self.ReceDeptName, self.RecePerson_A, self.SuperPerson,
                       self.MoveDeptName, self.MovePerson_A, self.reason,
                       self.MoveSeal, self.MoveDate]
        self.cb = [self.ReceDeptName, self.MoveSeal, self.MoveDeptName, self.reason, self.SealName_B]
        self.datatable = ['deptname', 'sealname', 'deptname', 'sealhandoverreason', 'sealname']
        self.cursor = self.j.cursor
        self.retranslateUi(Form)
        self.pt_new.clicked['bool'].connect(self.pt_add.setDisabled)
        self.pt_new.clicked['bool'].connect(self.pt_new.setEnabled)
        self.pt_new.clicked['bool'].connect(self.pt_new_click)
        self.cursor.execute("select * from sealhandover")
        data = self.cursor.fetchall()
        self.n = len(data) + 1
        for line in self.area_A:
            # self.pt_new.clicked['bool'].connect(line.clear)
            line.setEnabled(False)
            # self.pt_add.clicked['bool'].connect(line.clear)

        self.SealName_B.setEditable(True)
        self.setupAreaB()
        self.pt_add.clicked['bool'].connect(self.pt_add.setEnabled)
        self.pt_add.clicked['bool'].connect(self.pt_new.setDisabled)

        self.tableWidget.clicked.connect(self.table_slot)
        self.pt_del.clicked.connect(self.data_delete)
        self.pt_change.clicked.connect(lambda: self.data_change(Form))

        self.pt_print.clicked.connect(self.showPrintDialog)
        self.pt_query.clicked.connect(lambda: self.data_query(Form))
        QtCore.QMetaObject.connectSlotsByName(Form)

        # 添加数据
        self.pt_add.clicked['bool'].connect(self.add_record)
        self.cursor.execute("select * from sealhandover")
        self.data_show()

    def setupAreaB(self):
        sql = "select * from " + 'sealname'
        self.cursor.execute(sql)
        result = self.cursor.fetchall()
        if len(result) == 0:
            result.append('无')
        t = list()
        for row in result:
            t.append(row[0])
        self.SealName_B.addItems(t)

    def table_slot(self):
        for line in self.area_A:
            line.setEnabled(True)
        self.pt_del.setEnabled(True)
        self.pt_change.setEnabled(True)
        self.pt_add.setDisabled(True)
        self.pt_new.setDisabled(True)
        row = self.tableWidget.currentRow()
        self.text = self.tableWidget.item(row, 3).text()
        for (table, cb) in zip(self.datatable, self.cb):
            cb.clear()
            sql = "select * from " + table
            self.cursor.execute(sql)
            result = self.cursor.fetchall()
            if len(result) == 0:
                result.append('无')
            t = list()
            for row in result:
                t.append(row[0])
            cb.addItems(t)

    def pt_new_click(self):
        for line in self.area_A:
            line.setEnabled(True)
        for (table, cb) in zip(self.datatable, self.cb):
            cb.clear()
            sql = "select * from " + table
            self.cursor.execute(sql)
            result = self.cursor.fetchall()
            if len(result) == 0:
                result.append('无')
            t = list()
            for row in result:
                t.append(row[0])
            cb.addItems(t)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form",
                                        "<html><head/><body><p align=\"justify\"><span style=\" font-size:14pt; font-weight:600;\">印章交接管理</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "交接单号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "制单时间"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "印章编码"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "印章名称"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "移交人"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "移交人所在部门"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "交接人"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "交接人所在部门"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "监交人"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "交接原因"))
        self.label.setText(_translate("Form", "交接人所在部门"))
        self.label_3.setText(_translate("Form", "交接人"))
        self.label_7.setText(_translate("Form", "监交人"))
        self.label_8.setText(_translate("Form", "移交时间"))
        self.label_2.setText(_translate("Form", "移交人所在部门"))
        self.label_4.setText(_translate("Form", "移交人"))
        self.label_6.setText(_translate("Form", "移交印章"))
        self.label_9.setText(_translate("Form", "交接原因"))
        self.pt_new.setText(_translate("Form", "新建"))
        self.pt_add.setText(_translate("Form", "添加"))
        self.pt_change.setText(_translate("Form", "修改"))
        self.pt_del.setText(_translate("Form", "删除"))
        self.label_10.setText(_translate("Form", "制单时间"))
        self.label_11.setText(_translate("Form", "-->"))
        self.label_12.setText(_translate("Form", "交接人"))
        self.label_13.setText(_translate("Form", "移交人"))
        self.label_14.setText(_translate("Form", "印章编码/名称"))
        self.pt_query.setText(_translate("Form", "查询"))
        self.pt_print.setText(_translate("Form", "打印"))

        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)  # 设置只能选中整行
        self.tableWidget.setSelectionMode(QAbstractItemView.SingleSelection)  # 设置只能选中一行

    def data_delete(self):
        self.pt_del.setDisabled(True)
        self.pt_change.setDisabled(True)
        self.pt_add.setDisabled(True)
        self.pt_new.setEnabled(True)
        sql = "delete from sealhandover where sealname=" + repr(self.text)
        self.cursor.execute(sql)
        self.cursor.execute("select * from sealhandover")
        self.data_show()
        for line in self.area_A:
            line.setEnabled(False)
        self.pt_del.setDisabled(True)
        self.pt_change.setDisabled(True)
        self.pt_add.setDisabled(True)
        self.pt_new.setEnabled(True)
        for (table, cb) in zip(self.datatable, self.cb):
            cb.clear()
        self.j.conn.commit()

    def data_change(self, Form):
        self.pt_del.setDisabled(True)
        self.pt_change.setDisabled(True)
        self.pt_add.setDisabled(True)
        self.pt_new.setEnabled(True)
        table = ['receperson', 'superperson', 'handoverdate', 'movedeptname', 'moveperson',
                 'sealname', 'reason']
        area_A = [self.RecePerson_A, self.SuperPerson, self.MoveDate,
                  self.MoveDeptName, self.MovePerson_A, self.MoveSeal, self.reason
                  ]
        area_B = [self.RecePerson_A, self.SuperPerson, self.MovePerson_A, self.MoveDate]
        sql = "update sealhandover set recedeptname=" + repr(self.ReceDeptName.currentText())
        for (t, s) in zip(table, area_A):
            if s in area_B:
                sql = sql + "," + t + "=" + repr(s.text())
            else:
                sql = sql + "," + t + "=" + repr(s.currentText())
        sql = sql + " where sealname=" + repr(self.text)
        self.cursor.execute(sql)
        self.j.conn.commit()
        self.cursor.execute("select * from sealhandover")
        self.data_show()

    # insert,只是简单插入固定数据, 后期应该不需要
    def data_show(self):
        rowPosition = self.tableWidget.rowCount()
        for rP in range(0, rowPosition):    self.tableWidget.removeRow(0)

        row = self.cursor.fetchall()
        for (r, i) in zip(row, range(0, len(row))):
            self.tableWidget.insertRow(i)
            item_id = QTableWidgetItem(r[8])
            item_id.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)  # 设置物件的状态为只可被选择（未设置可编辑）
            sql2 = "select sealnum from seal where sealname=" + repr(r[0])
            self.cursor.execute(sql2)
            result = self.cursor.fetchall()
            t = list()
            for x in result:
                t.append(x[0])
            item_DocuDateStart = QTableWidgetItem(r[9])
            item_DocuDateStart.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            item_SealNum = QTableWidgetItem(t[0])
            item_SealNum.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            item_SealName = QTableWidgetItem(r[0])
            item_SealName.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            item_pos = QTableWidgetItem("(1,2)")
            item_pos.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)  # 设置物件的状态为只可被选择

            item_MoveDeptName = QTableWidgetItem(r[2])
            item_MoveDeptName.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            item_MovePerson_A = QTableWidgetItem(r[1])
            item_MovePerson_A.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            item_ReceDeptName = QTableWidgetItem(r[4])
            item_ReceDeptName.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            item_RecePerson_A = QTableWidgetItem(r[3])
            item_RecePerson_A.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            item_SuperPerson = QTableWidgetItem(r[5])
            item_SuperPerson.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            item_reason = QTableWidgetItem(r[6])
            item_reason.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)

            self.tableWidget.setItem(i, 0, item_id)
            self.tableWidget.setItem(i, 1, item_DocuDateStart)
            # self.tableWidget.setItem(i, 2, item_DocuDateEnd)
            self.tableWidget.setItem(i, 2, item_SealNum)
            self.tableWidget.setItem(i, 3, item_SealName)
            self.tableWidget.setItem(i, 4, item_MovePerson_A)
            self.tableWidget.setItem(i, 5, item_MoveDeptName)
            self.tableWidget.setItem(i, 6, item_RecePerson_A)
            self.tableWidget.setItem(i, 7, item_ReceDeptName)
            self.tableWidget.setItem(i, 8, item_SuperPerson)
            self.tableWidget.setItem(i, 9, item_reason)

    def data_query(self, Form):
        sql = "select * from sealhandover where"
        text1 = self.MovePerson_B.text()
        text2 = self.RecePerson_B.text()
        date1 = self.DocuDate_s.text()
        date2 = self.DocuDate_e.text()
        if len(text1) != 0 and len(text2) != 0:
            sql = sql + " moveperson=" + repr(text1) + " and receperson=" + repr(text2) + " and"
        elif len(text1) != 0:
            sql = sql + " moveperson=" + repr(text1) + " and"
        elif len(text2) != 0:
            sql = sql + " receperson=" + repr(text2) + " and"
        sql = sql + " handtime>=" + repr(date1) + "and handtime<=" + repr(date2) + " and sealname=" + repr(
            self.SealName_B.currentText())
        self.cursor.execute(sql)
        result = self.cursor.fetchall()
        if len(result) == 0:
            QtWidgets.QMessageBox.information(Form, 'Message',
                                              "查询失败!无数据！")
            for i in range(0, self.tableWidget.rowCount()):
                self.tableWidget.removeRow(0)
            return
        else:
            QtWidgets.QMessageBox.information(Form, 'Message',
                                              "查询成功!")
        self.cursor.execute(sql)
        self.data_show()

    def add_record(self):
        """
        向数据库中添加数据
        :return:
        """
        SealName = self.MoveSeal.currentText()
        MovePerson_A = self.MovePerson_A.text()
        MoveDeptName = self.MoveDeptName.currentText()
        RecePerson_A = self.RecePerson_A.text()
        ReceDeptName = self.ReceDeptName.currentText()
        SuperPerson = self.SuperPerson.text()
        reason = self.reason.currentText()
        handoverdate = self.MoveDate.text()
        handdate = QtCore.QDate.currentDate().toString("yyyy/MM/dd")
        order_code = "T" + str(self.n).zfill(6)  # 制单编码
        table = [MovePerson_A, MoveDeptName, RecePerson_A, ReceDeptName, SuperPerson, reason, handoverdate, order_code,
                 handdate]
        sql = "insert into sealhandover values(" + repr(SealName)
        for t in table:
            sql = sql + "," + repr(t)
        sql = sql + ")"
        self.cursor.execute(sql)
        self.j.conn.commit()
        self.n = self.n + 1
        self.cursor.execute("select * from sealhandover")
        for line in self.area_A:
            # self.pt_new.clicked['bool'].connect(line.clear)
            line.setEnabled(False)
        self.data_show()
        for line in self.area_A:
            self.pt_add.clicked['bool'].connect(line.clear)
        # 弹出对话框，提交成功

    def data(self, u):
        self.j = u

    def showPrintDialog(self):
        headers = ['交接单号','制单时间','印章编码','印章名称',
                                        '移交人', '移交人所在部门', '交接人','交接人所在部门',
                                        '监交人', '交接原因']
        self.df = pd.DataFrame(columns=headers)
        df_set = {}
        for j in range(self.tableWidget.columnCount()):
            df_set[headers[j]]=[]
            for i in range(self.tableWidget.rowCount()):
                df_set[headers[j]].append(self.tableWidget.item(i, j).text())

        self.df = pd.DataFrame(df_set)
        fn, _ = QFileDialog.getSaveFileName(self.Form, 'Speichern unter', None, 'Excel Dateien (.xlsx);;Alle Dateien()')
        try:
            if fn != '':
                if QFileInfo(fn).suffix() == "": fn += '.xlsx'
            self.df.to_excel(fn, index=False)
        except: pass
