# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import KeepUse, PrintUse,HandOver

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.md = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.keep_use = QtWidgets.QPushButton(self.centralwidget)
        self.keep_use.setGeometry(QtCore.QRect(120, 87, 521, 71))
        self.keep_use.setObjectName("keep_use")
        self.print_use = QtWidgets.QPushButton(self.centralwidget)
        self.print_use.setGeometry(QtCore.QRect(120, 187, 241, 61))
        self.print_use.setObjectName("print_use")
        self.hand_over = QtWidgets.QPushButton(self.centralwidget)
        self.hand_over.setGeometry(QtCore.QRect(400, 187, 241, 61))
        self.hand_over.setObjectName("hand_over")
        self.use = QtWidgets.QPushButton(self.centralwidget)
        self.use.setGeometry(QtCore.QRect(120, 287, 241, 61))
        self.use.setObjectName("use")
        self.deactivate = QtWidgets.QPushButton(self.centralwidget)
        self.deactivate.setGeometry(QtCore.QRect(400, 287, 241, 61))
        self.deactivate.setObjectName("deactivate")
        self.log = QtWidgets.QPushButton(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(120, 377, 521, 71))
        self.log.setObjectName("log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menuBar)
        self.action_relog = QtWidgets.QAction(MainWindow)
        self.action_relog.setObjectName("action_relog")
        self.action_lock = QtWidgets.QAction(MainWindow)
        self.action_lock.setObjectName("action_lock")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menu_2.addSeparator()
        self.menu_4.addAction(self.action_relog)
        self.menu_4.addAction(self.action_lock)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_exit)
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.action_exit.triggered.connect(MainWindow.close)
        self.action_relog.triggered.connect(MainWindow.close)
        self.action_lock.triggered.connect(self.lock)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #跳转
        self.keep_use_form = None
        self.keep_use.clicked.connect(self.jump_to_keep_use)

        self.print_use_form = None
        self.print_use.clicked.connect(self.jump_to_print_use)

        self.hand_over_form = None
        self.hand_over.clicked.connect(self.jump_to_hand_over)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.keep_use.setText(_translate("MainWindow", "印章保管与使用标准管理 "))
        self.print_use.setText(_translate("MainWindow", "刻制与领用管理"))
        self.hand_over.setText(_translate("MainWindow", "交接管理"))
        self.use.setText(_translate("MainWindow", "使用管理   "))
        self.deactivate.setText(_translate("MainWindow", "停用管理"))
        self.log.setText(_translate("MainWindow", "日志管理    "))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "返回"))
        self.menu_4.setTitle(_translate("MainWindow", "操作"))
        self.action_relog.setText(_translate("MainWindow", "重新登录"))
        self.action_lock.setText(_translate("MainWindow", "锁定系统"))
        self.action_lock.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.action_exit.setText(_translate("MainWindow", "退出"))
        self.action_exit.setShortcut(_translate("MainWindow", "Alt+X"))

    def jump_to_keep_use(self):        #这一块注意，是重点从主界面跳转到Demo1界面，主界面隐藏，如果关闭Demo界面，主界面进程会触发self.form.show()会再次显示主界面
        #self.md.hide()         #如果没有self.form.show()这一句，关闭Demo1界面后就会关闭程序

        if self.keep_use_form==None:
            self.keep_use_form = QtWidgets.QDialog()
            ui = KeepUse.Ui_KeepUse()
            ui.innitial(self.data)
            ui.setupUi(self.keep_use_form)
            self.keep_use_form.show()
            self.keep_use_form.exec_()
            self.keep_use_form = None
        else:
            self.keep_use_form.raise_()
        #self.md.show()
    def jump_to_print_use(self):        #这一块注意，是重点从主界面跳转到Demo1界面，主界面隐藏，如果关闭Demo界面，主界面进程会触发self.form.show()会再次显示主界面
        #self.md.hide()            #如果没有self.form.show()这一句，关闭Demo1界面后就会关闭程序

        if self.print_use_form==None:
            self.print_use_form = QtWidgets.QDialog()
            ui = PrintUse.Ui_PrintUse()
            ui.innitial(self.data)
            ui.setupUi(self.print_use_form)
            self.print_use_form.show()
            self.print_use_form.exec_()
            self.print_use_form = None

        else:
            self.print_use_form.raise_()
        #self.md.show()
    def initial(self,data):
        self.data=data

    def lock(self):
        text,ok  =   QtWidgets.QInputDialog.getText(None,"锁定",
                                    "请输入密码",QtWidgets.QLineEdit.Password)
        if text != self.password:
            self.lock()
                
    def jump_to_hand_over(self):
        if self.hand_over_form == None:
            self.hand_over_form = QtWidgets.QDialog()
            ui = HandOver.Ui_HandOver()
            ui.data(self.data)
            ui.setupUi(self.hand_over_form)
            self.hand_over_form.show()
            self.hand_over_form.exec_()
            self.hand_over_form = None
        else:
            self.hand_over_form.raise_()
