# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keep_use.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import CurveApply

class Ui_PrintUse(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 420)
        self.apply = QtWidgets.QPushButton(Dialog)
        self.apply.setGeometry(QtCore.QRect(130, 80, 301, 61))
        self.apply.setObjectName("apply")
        self.print = QtWidgets.QPushButton(Dialog)
        self.print.setGeometry(QtCore.QRect(130, 190, 301, 61))
        self.print.setObjectName("print")
        self.get = QtWidgets.QPushButton(Dialog)
        self.get.setGeometry(QtCore.QRect(130, 300, 301, 61))
        self.get.setObjectName("information")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(190, 0, 271, 61))
        self.title.setObjectName("title")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.curve_apply_form = None
        self.apply.clicked.connect(self.jump_to_curve_apply)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.apply.setText(_translate("Dialog", "印章刻制申请管理"))
        self.print.setText(_translate("Dialog", "印章刻制管理"))
        self.get.setText(_translate("Dialog", "印章领用管理"))
        self.title.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">刻制与领用管理 </span></p></body></html>"))
        self.title.setWhatsThis(_translate("Dialog", "<html><head/><body><p>sdasdasdasdasd</p></body></html>"))
        self.title.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">刻制与领用管理 </span></p></body></html>"))

    def jump_to_curve_apply(self):
        if self.curve_apply_form == None:
            self.curve_apply_form = QtWidgets.QMainWindow()
            self.ui = CurveApply.Ui_CurveApply()
            self.ui.innitial(self.data)
            self.ui.setupUi(self.curve_apply_form)
            self.curve_apply_form.show()
        elif isinstance(self.curve_apply_form, QtWidgets.QMainWindow):
            self.curve_apply_form.show()
            self.curve_apply_form.raise_()
    def innitial(self,u):
        self.data=u